### ISSUE TITLE
[BUG] Directions A) Install Standalone - Production throws error

### ISSUE THREAD

**Issue by Chapoton** [flashtag/development#11]
When I clone a existing repo, in this case the Flashtag CMS itself
`https://github.com/flashtag/cms.git`
I get an error when I run `php artisan flashtag:install` in the command line.

Here is a screenshot of the error.

![screen shot 2016-05-03 at 4 18 06 pm](https://cloud.githubusercontent.com/assets/4986993/15001277/28d5fc2a-114b-11e6-85a1-ee0dfefc5e0d.png)

I see it's because I did not create a .env file. Should the install script check for this first?

Also, I'm not if the directions are wrong, or if I'm missing a step or two, but I had to follow the following steps in order to properly run `php artisan flashtag:install`
1.  `vendor/bin/homestead make`
2. `vagrant up`
3. `vagrant ssh`
4. CD in the directory
5. `php artisan flashtag:install`

The instructions just say to run `php artisan flashtag:install` without any mention of Vagrant, ssh, etc.

**Comment by ryanwinchester** [comment]
Thanks :)
